// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pomodoro.Postgres;

#nullable disable

namespace Pomodoro.Postgres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509163629_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pomodoro.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Dictionary<string, int>>("DailyLog")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ElapsedSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TotalSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Pomodoro.Domain.Entities.Session", b =>
                {
                    b.OwnsOne("Pomodoro.Domain.Entities.TimerSettings", "TimerSettings", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Cycles")
                                .HasColumnType("integer");

                            b1.Property<int>("FocusMinutes")
                                .HasColumnType("integer");

                            b1.Property<int>("LongBreakMinutes")
                                .HasColumnType("integer");

                            b1.Property<int>("ShortBreakMinutes")
                                .HasColumnType("integer");

                            b1.HasKey("SessionId");

                            b1.ToTable("Sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("TimerSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
